# Site settings
title: Netafilter
description: > # this means to ignore newlines until "baseurl:"
 Indian MP, MLA, Councillor statistics, information and comparisons based on open data from the government.
 Netafilter can easily filter your polticial candidate based on education, assets, criminal cases, party and constituency from the affidavit information

# Build settings
markdown: kramdown
